name: predict

on:
  workflow_dispatch:

jobs:
  run-prediction:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tensorflow numpy Pillow matplotlib

    - name: Run prediction script
      run: |
        python predict.py > result.txt

    - name: Upload result.txt
      uses: actions/upload-artifact@v4
      with:
        name: prediction-result
        path: result.txt