name: Auto Train Model

on:
  schedule:
    - cron: '0 3 * * *'   # Every day at 3 AM UTC
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install TensorFlow
        run: pip install tensorflow

      - name: Run training script
        run: python train_model.py

      - name: Upload trained model
        uses: actions/upload-artifact@v4
        with:
          name: freshness_model
          path: freshness_model.h5